---
title: "Topdown_Pilot_preprocessing"
author: "wujiaqi"
date: "2024-11-12"
output: html_document
---

```{r}
# load packages
# 使用pacman管理包
if (!require(pacman)){
        install.packages("pacman")
        library(pacman)
}

# 使用p_load批量加载包并自动下载并加载未安装的包
pacman::p_load('tidyverse', 'ggplot2')
```


```{r warning=FALSE}
setwd("C:/1_Postgraduate/TaskRelevance/1_Study1_Task_Target/1_4_Analysis")

df_raw <- list.files(file.path("../1_3_RawData"), pattern = "exp1_.*\\.csv$") %>%
  # 对读取到的所有.out文件x都执行函数read.table
  lapply(function(x) read.csv(file.path("../1_3_RawData", x), header = TRUE)) %>%
    # 读取被试人口学信息
  lapply(function(df) mutate(df,subj_idx = as.numeric(jsonlite::fromJSON(response[5])$Q0), 
          gender = jsonlite::fromJSON(response[6]),
          year = jsonlite::fromJSON(response[7])$Q0,
          education = jsonlite::fromJSON(response[8])$Q0,
          dist = view_dist_mm[9],
          rt = as.numeric(rt),
          success = as.character(success),
          timeout = as.character(timeout),
          correct = as.character(correct),
          correct = gsub("TRUE", "true", correct),
          RightLable = as.character(RightLable)))%>%
  bind_rows()
```

```{r}
df <- df_raw %>% 
  # 选择变量
  select(subj_idx, 
         gender, # 男0女1
         year, 
         #education, 
         #dist, 
         rt, 
         correct_response, 
         correct, 
         key_press, 
         # Image, 
         word, # labels in matching task
         shape, # shapes in matching task
         condition, # task types
         trial_type,
         ) %>%
  # 选择正式实验试次
  dplyr::filter(
    trial_type == "psychophysics" &
    condition != "prac_matching_task" &
    condition != "prac_classify_self" &
    condition !="prac_classify_friend" &
    condition !="prac_classify_stranger"
  )%>%

  # 剔除无关变量
  select(
         -trial_type,
         )
  # 1-24为pilot version 1，25-30为pilot version 2
  # filter(!(sub_inx %in% 1:24))
df

# write.csv(df,file = "C:/1_Postgraduate/TaskRelevance/1_Study1_Task_Target/1_4_Analysis/exp1_long.csv")

```

# 图形标签匹配任务：ACC数据集
```{r}
# 计算每个被试平均正确率
df.match.acc <- df%>%
  filter(condition == 'matching_task')%>%
  dplyr::mutate(
    matchness = ifelse(word == shape, "match", "mismatch"),
    ACC = ifelse(correct == "true",1,0)
  )%>%
  dplyr::group_by(
    subj_idx,
    gender,
    year,
    matchness,
    shape
  )%>%
  dplyr::summarise(
    N = length(ACC),
    countN = sum(ACC),
    ACC = sum(ACC) / length(ACC)
  )%>%
  # 1-12行为材料1，13-24行为材料2
  mutate(material = case_when(
    subj_idx %in% c(1:12) ~ 1,  
    TRUE ~ 2,                
  ))


# 图形标签匹配任务：ACC数据集(适用R)
df.match.acc

# 图形标签匹配任务：ACC数据集（适用JASP）
df.match.acc <- df.match.acc %>%
  select(subj_idx,gender, year, material, matchness,shape,ACC) %>%
  pivot_wider(names_from = c("shape", "matchness"), values_from = "ACC")
df.match.acc
  
# write_excel_csv(df.match.acc,file = "C:/1_Postgraduate/TaskRelevance/1_Study1_Task_Target/1_4_Analysis/exp1_matching_acc.csv")

```

# 图形标签匹配任务：RT数据集
```{r}
# 计算每个被试平均反应时
df.match.rt <- df %>%
  dplyr::filter(condition == 'matching_task')%>%
  dplyr::mutate(
    matchness = ifelse(word == shape, "match", "mismatch")
  )%>%
  # 剔除错误试次
  dplyr::filter(correct == "true")%>%
  mutate(material = case_when(
    subj_idx %in% c(1:12) ~ 1,  
    TRUE ~ 2,                
  ))

# the number of RT out of range: rt<200ms or rt >1500ms
rt.out.range <- sum(df.match.rt$rt < 200 | df.match.rt$rt > 1500)
rt.out.range

df.match.rt <- df.match.rt %>%
  group_by(
    subj_idx,
    gender,
    year,
    material,
    matchness,
    shape
  )%>%
  summarize(
    rt = mean(rt, na.rm = TRUE)
    )

# 分类任务RT数据（适用R）
df.match.rt

# 分类任务RT数据（适用JASP）
df.match.rt <- df.match.rt%>%
  pivot_wider(names_from = c("shape", "matchness"), values_from = "rt")
df.match.rt

# write_excel_csv(df.match.rt, "C:/1_Postgraduate/TaskRelevance/1_Study1_Task_Target/1_4_Analysis/exp1_matching_rt.csv")
```

# 分类任务：ACC数据集
```{r}
# 计算每个被试平均正确率
df.classify.acc <- df %>%
  filter(condition != 'matching_task')%>%
  dplyr::mutate(ACC = ifelse(correct == "true",1,0)) %>%
  dplyr::group_by(
    subj_idx,
    gender,
    year,
    shape,
    condition,
    )%>%
  dplyr::summarise(
    N = length(ACC),
    countN = sum(ACC),
    ACC = sum(ACC) / length(ACC)
  )%>%
  mutate(material = case_when(
    subj_idx %in% c(1:12) ~ 1,  
    TRUE ~ 2,                
  ))
  

# 分类任务ACC数据（适用R）
df.classify.acc

# 分类任务ACC数据（适用JASP）
df.acc <- df.classify.acc %>%
  select(subj_idx,gender, year, material, condition,shape,ACC) %>%
  pivot_wider(names_from = c("shape"), values_from = "ACC")
df.acc
  
# write_excel_csv(df.acc,file = "C:/1_Postgraduate/TaskRelevance/1_Study1_Task_Target/1_4_Analysis/exp1_classify_acc.csv")
```

# 分类任务：RT数据集
```{r}
# 计算每个被试平均反应时
df.classify.rt <- df %>%
  dplyr::filter(condition != 'matching_task')%>%
  select(everything())%>%
  # 剔除错误试次
  dplyr::filter(correct == "true")%>%
  mutate(material = case_when(
    subj_idx %in% c(1:12) ~ 1,  
    TRUE ~ 2,                
  ))

# the number of RT out of range: rt<200ms or rt >1500ms
rt.out.range <- sum(df.classify.rt$rt < 200 | df.classify.rt$rt > 1500)
rt.out.range

df.classify.rt <- df.classify.rt %>%
  group_by(
    subj_idx,
    gender,
    year,
    material,
    condition,
    shape
  )%>%
  summarize(
    rt = mean(rt, na.rm = TRUE)
    )

# 分类任务RT数据（适用R）
df.classify.rt

# 分类任务RT数据（适用JASP）
df.rt <- df.classify.rt%>%
  pivot_wider(names_from = c("shape"), values_from = "rt")
df.rt

# write_excel_csv(df.rt, "C:/1_Postgraduate/TaskRelevance/1_Study1_Task_Target/1_4_Analysis/exp1_classify_rt.csv")
```
