---
title: "Topdown_pilot_single_subject_analysis"
author: "wujiaqi"
date: "2025-03-25"
output: html_document
---
```{r}
# load packages
# 使用pacman管理包
if (!require(pacman)){
        install.packages("pacman")
        library(pacman)
}

# 使用p_load批量加载包并自动下载并加载未安装的包
pacman::p_load('tidyverse', 'ggplot2')
```

```{r warning=FALSE}
setwd("C:/1_Postgraduate/TaskRelevance/2_Study2_Task_Relevence/2_4_Analysis")

df_raw <- list.files(file.path("../2_3_RawData"), pattern = "exp2_.*\\.csv$") %>%
  # 对读取到的所有.out文件x都执行函数read.table
  lapply(function(x)
    read.csv(file.path("../2_3_RawData", x), header = TRUE)) %>%
  # 读取被试人口学信息
  lapply(
    function(df)
      mutate(
        df,
        # subj_idx = as.numeric(jsonlite::fromJSON(response[5])$Q0),
        gender = jsonlite::fromJSON(response[5]),
        year = jsonlite::fromJSON(response[6])$Q0,
        education = jsonlite::fromJSON(response[7])$Q0,
        dist = view_dist_mm[9],
        rt = as.numeric(rt),
        success = as.character(success),
        timeout = as.character(timeout),
        correct = as.character(correct),
        correct = gsub("TRUE", "true", correct),
        ismatch = as.character(ismatch),
        ismatch = tolower(ismatch),
      )
  ) %>%
  bind_rows()
```

```{r}
df <- df_raw %>%
  # 选择变量
  select(
    subj_idx,
    gender,       # 男0女1
    year,
    rt,
    correct_response,
    correct,
    key_press,
    shapes,       # 配对的标签（图形的社会属性
    pres_labels,    # 呈现的标签
    pres_shapes,    # 呈现的图形
    pres_colors,    # 呈现的颜色
    paired_colors,    # 配对的颜色
    ismatch,
    condition,    # 图形-标签/呈现颜色-配对颜色 是否匹配
    trial_type,    # task types
  ) %>%
  # 选择正式实验试次
  dplyr::filter(trial_type == "psychophysics" &
                  condition != "TR_prac" &
                  condition != "TIR_prac") %>%
  # 再次剔除无关变量
  mutate(
    year = as.numeric(year),
    year = 2025 - year,
    acc = ifelse(correct == "true", 1, 0),
    ismatch = ifelse(ismatch == "true", 1, 0),
  ) %>%
  select(
    -trial_type, 
    -correct,
    -correct_response)%>%
  filter(subj_idx %in% c(41))

head(df)


```

```{r}
# 试次数&准确率检查
df.check <- df %>% 
  group_by(subj_idx, condition, shapes, ismatch) %>%
  # group_by(subj_idx) %>%
  summarise(
    N = length(acc), 
    N_crrct = sum(acc),
    ACC = sum(acc)/length(acc)
    ) 

df.check
```
```{r}
# 被试疲劳/练习效应检查
# 会存在练习效应，中后段会出现疲劳效应，需要提醒被试注意休息，以及要求又快又准，我们同时追求速度和准确性！！
df.fatigue <- df %>%
  group_by(subj_idx, condition) %>%
  mutate(trial_index = row_number(),
         phrase = case_when(
           trial_index <= round(n() / 3) ~ "前期",
           trial_index >  round(n() / 3) & trial_index <= round(2 * n() / 3) ~ "中期",
           TRUE ~"后期"),
         phrase = factor(phrase, levels = c("前期", "中期", "后期"))
         ) %>%
  group_by(subj_idx, condition, phrase) %>%
  summarise(
    mean_rt = mean(rt, na.rm = TRUE),
    sd_rt = sd(rt, na.rm = TRUE),
    n_trials = n()
  ) 

df.fatigue
```


```{r}
# 被试分类任务的反应时间分布
df.norm <- df %>% 
  # filter(subj_idx == 32)%>%
  # filter(condition != "matching_task") %>%
    # group_by(subj_idx) %>%
  group_by(subj_idx, condition, shapes, ismatch) %>%
  drop_na(rt) %>%
  summarise(
    rt.mean = mean(rt, na.rm = TRUE),
    rt.sd = sd(rt, na.rm = TRUE),
    density = dnorm(x=rt, mean=rt.mean, sd=rt.sd),
    rt=rt,
    ) 
df.norm

```



```{r}
ggplot(df.norm, aes(x=rt, y=density, color=shapes)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  facet_wrap(~subj_idx+condition+ismatch, ncol = 4) +
  theme(
    legend.position = "right",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", fill = NA)
    ) +
  labs(title = "Reaction time distribution of each subject",
       x = "Reaction time (ms)",
       y = "Density")
```


